### ISSUE TITLE
directory structure

### ISSUE THREAD

**Issue by lea-hagen** [BEAST-Fitting/megabeast#19]
The BEAST has a fairly well-defined directory structure - from the folder it's run in, the data files are assumed to be in `./data/` (and new data-related files go there too), and the various modeling outputs are put in `./projectname/`.  The last BEAST step of doing the spatial reorganization lets the user put the files anywhere, and megabeast gets run from inside that folder.  I'm thinking it would be nice to standardize that part too.

**Comment by karllark** [comment]
Not sure I fully understand.  Please include more details or let's discuss in person.
