### ISSUE TITLE
Incorrect pixel coordinates in naive map script

### ISSUE THREAD

**Issue by drvdputt** [BEAST-Fitting/megabeast#33]
I've been using the make_naive_maps script for a while now, and I've always felt like there was something off about the coordinate system.

I believe I have now found the error. There's two mistakes when the RA and Dec of the sources are converted to pixel coordinates of the map WCS.

- The code loops over the pixels using range(n_x) and range(n_y), which start at 0. But in`regions_for_objects`, we have `pixcrd = wcs_info.wcs_world2pix(world, 1)`, which asks for a  1-based index instead. This type of pixel coordinate is what's shown in DS9 for example. But when accessing the data array using numpy, 0-based coordinates are needed.
- The pixel coordinates in a fits image are relative to the **center** of the pixels, not the bottom left corner. The bottom left corner of pixel (1,1) is at (0.5, 0.5), and the top left corner at (1.5, 1.5) in case of 1-based coordinates. For 0-based, this pixel becomes (0, 0), with corners (-0.5, -0.5) and (0.5, 0.5) respectively. 

So 1.6 would belong belongs to pixel 2, not pixel 1. Therefore, the floating point pixel coordinates should be **rounded**, not truncated.
```
# this is wrong
x = pixcrd[:, 0].astype(int)
# this should be ok
x = np.rint(pixcrd[:, 0]).astype(int)
```

This is fixed in my own branch, but there are some other changes. I'll put in a clean pull request once I'm more sure that my own code is correct.

**Comment by karllark** [comment]
Great.  Looking forward to the PR!

**Comment by karllark** [comment]
@drvdputt : is this still a bug or has it been fixed?  Or am I still waiting for the PR?  :-)

**Comment by drvdputt** [comment]
I did a quick search through the issues, and found that @lea-hagen already replaced this code in PR #39. So this can be closed.
