### ISSUE TITLE
Distance priors for MegaBEAST

### ISSUE THREAD

**Issue by kmcquinn** [BEAST-Fitting/megabeast#38]
- Distance priors need to be flexible enough in MegaBEAST to allow for distance changes of the order a few tenths of a mag (maybe 0.5? more?) in distance modulus.

- Depending on how distances are fit in BEAST, the prior may simply be an updated best distance value. But, if BEAST is fitting distances based on specific features in a CMD, the input may be an updated zeropoint calibration. For example, if the horizontal branch was used in BEAST, then the zeropoint could be changed (or the uncertainties on the zeropoint). If the TRGB was used, the zeropoint could similarly be changed. If both features are used, then this is more difficult, and may require a re-run of the BEAST?

**Comment by karllark** [comment]
I'm not sure I understand how to implement what is being suggested here.
For the distance prior in the megabeast, it is something that will effect all the stars, not just specific parts of the HR diagram.  
But plan is to set up the fitting to be able to limit it (if desired) to specific HR diagram region (see #43).  Does this address this point?

**Comment by kmcquinn** [comment]
Perhaps my comment is off-base for how MegaBEAST will do things. 

If I were to measure a distance from a CMD, I could fit, for example, the TRGB or the Horizontal Branch. Each of these has its own calibration. Fitting each individually and applying the calibrations can result in slightly different answers.  Thus, it is sometimes useful to consider these distances determinations separately (fit from different parts of the CMD).

If MegaBEAST is fitting distances from the full CMD, then my comment can be ignored.  Does that help?

**Comment by karllark** [comment]
Yes, this helps. I think I will close this issue for now.  If once we get the v1.0 of the megabeast running and this is an issue we do need to address, then we can reopen this issue or open another.
